# Generated by Django 4.1.5 on 2023-04-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=255)),
                ('token_id', models.CharField(max_length=255))
            ],
        ),

        migrations.CreateModel(
          name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits = 10)),
                ('seller', models.CharField(max_length=255)),
                ('image_id', models.CharField(max_length=255)),
                ('num_sales', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('approval_status', models.IntegerField())
            ],
        ),

        migrations.CreateModel(
          name='ShoppingCart',
            fields = [
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('order_status', models.IntegerField()),
                ('order_place_date', models.DateTimeField())
            ],
        ),


        migrations.CreateModel(
          name="ShoppingCartItem",
            fields = [
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_cart_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField())
            ],
        ),

    ]
